#!/bin/bash

# Parse passed arguments
imagePath=$1
kernelPath=$2
kernelSize=$3

echo $imagePath $kernelPath $kernelSize

# Seperate the image into its constituent red, green, and blue pixel values (bands)
python3 imageToPixelRGB.py $imagePath

# Collect useful image metadata generated by the previous command
imageMode=$(head -1 imageConfig.txt)
imageWidth=$(head -2 imageConfig.txt | tail -1)
imageHeight=$(head imageConfig.txt | tail -1)

echo $imageMode $imageWidth $imageHeight

# Use the kernel to convolve each image band
g++ main.cpp
./a.out $imageWidth $imageHeight $kernelPath $kernelSize

# Combine the transformed RGB pixels back together and generate the final image
python3 pixelRGBToImage.py $imageMode $imageWidth $imageHeight